openai:
  api_key: "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"
  model: "gpt-4o"
  temperature: 0
  max_tokens: 100

scraper:
  query: "Solana"
  max_tweets: 50
  days_lookback: 7

Twitter: 
  key : "nk4WRAnq8pqXonhUaheZO70ac"
  secret : "jec29ljDq6n6VHoeD8yMmCwiqOCIy5oxIH06rzq1xpGDKEz7YF"
  token : "AAAAAAAAAAAAAAAAAAAAAJgN0QEAAAAA2uMlcKJrVC07WYNBjfMuSdBI3fo%3DehtyJLpBup75s8YojnH2km25MOnJprNhP9Vy1c68Y0MVgMZvjn"
